/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const NewsCategory = IDL.Variant({
  'news' : IDL.Null,
  'event' : IDL.Null,
});
export const NewsEvent = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : NewsCategory,
});
export const AdmissionEnquiry = IDL.Record({
  'applicantName' : IDL.Text,
  'programOfInterest' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Notice = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isImportant' : IDL.Bool,
  'date' : Time,
});

export const idlService = IDL.Service({
  'addNewsEvent' : IDL.Func([IDL.Text, IDL.Text, Time, NewsCategory], [], []),
  'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'getActiveNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], []),
  'getAllAdmissionEnquiries' : IDL.Func([], [IDL.Vec(AdmissionEnquiry)], []),
  'getAllContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], []),
  'submitAdmissionEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'toggleNewsEventStatus' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const NewsCategory = IDL.Variant({ 'news' : IDL.Null, 'event' : IDL.Null });
  const NewsEvent = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : NewsCategory,
  });
  const AdmissionEnquiry = IDL.Record({
    'applicantName' : IDL.Text,
    'programOfInterest' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Notice = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isImportant' : IDL.Bool,
    'date' : Time,
  });
  
  return IDL.Service({
    'addNewsEvent' : IDL.Func([IDL.Text, IDL.Text, Time, NewsCategory], [], []),
    'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'getActiveNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], []),
    'getAllAdmissionEnquiries' : IDL.Func([], [IDL.Vec(AdmissionEnquiry)], []),
    'getAllContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], []),
    'submitAdmissionEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'toggleNewsEventStatus' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };