/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionEnquiry {
  'applicantName' : string,
  'programOfInterest' : string,
  'email' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface ContactSubmission {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type NewsCategory = { 'news' : null } |
  { 'event' : null };
export interface NewsEvent {
  'title' : string,
  'date' : Time,
  'description' : string,
  'isActive' : boolean,
  'category' : NewsCategory,
}
export interface Notice {
  'title' : string,
  'content' : string,
  'isImportant' : boolean,
  'date' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'addNewsEvent' : ActorMethod<[string, string, Time, NewsCategory], undefined>,
  'addNotice' : ActorMethod<[string, string, boolean], undefined>,
  'getActiveNewsEvents' : ActorMethod<[], Array<NewsEvent>>,
  'getAllAdmissionEnquiries' : ActorMethod<[], Array<AdmissionEnquiry>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'submitAdmissionEnquiry' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'toggleNewsEventStatus' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];